# Site settings
title: Nice Blog
name: Nice Blog # your name
email: youremail@example.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itisbenjamin.github.io/Nice_Blog" # the base hostname & protocol for your site
twitter_username: itisbenjamin1 # your Twitter username
github_username: itisbenjamin # your Github username
disqus_username: itisbenjamin # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

######### Do not touch these bellow if you do not know what they mean########

# Build settings
permalink: none
markdown: kramdown
