# Site settings
title: Nokbeondev
name: NokbeonDev # your name
email: nokbeondev@gmail.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one
google_font: "Nanum+Gothic:400,700"

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
